In [1]:
import numpy as np

# Creating Numpy Arrays

In [2]:
mylist = [[1, 3], [2, 3]]
array = np.array(mylist)

In [3]:
array

array([[1, 3],
       [2, 3]])

In [4]:
np.arange(start = 2, stop = 15, step = 3)

array([ 2,  5,  8, 11, 14])

In [5]:
np.zeros(shape = [2, 5], dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
np.linspace(start = 0, stop = 20, num = 5)

array([ 0.,  5., 10., 15., 20.])

In [7]:
np.eye(3)    #Creates a identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.rand(2, 5)

array([[0.28689384, 0.25819969, 0.08220938, 0.56470745, 0.82115501],
       [0.34928063, 0.93826939, 0.85611045, 0.40915171, 0.55752861]])

In [9]:
np.random.randn(2, 5)

array([[-0.29571588,  1.17118298, -0.87891929,  0.40835884,  1.07849638],
       [-1.99599242, -0.42208397,  0.78923313, -0.55768527,  1.21425938]])

In [10]:
np.random.seed(3)
np.random.randint(low = 0, high = 50, size = 20)

array([42, 24,  3,  8,  0, 21, 19, 10, 43, 41, 10, 21, 38, 32, 20, 44, 29,
       39, 14, 26])

In [11]:
array = np.arange(0, 30)
array = array.reshape(2, 15)

In [12]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Numpy Selection and Indexing

In [13]:
array = np.arange(0, 20, 2)
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
print(f"Index 1 to 5 {array[1:5]}")
print(f"Index 1 to end {array[1:]}")
print(f"Index start to 5 {array[:5]}")
print(f"Index everything {array[:]}")

Index 1 to 5 [2 4 6 8]
Index 1 to end [ 2  4  6  8 10 12 14 16 18]
Index start to 5 [0 2 4 6 8]
Index everything [ 0  2  4  6  8 10 12 14 16 18]


In [15]:
array[0:6] = -1
print(array)

[-1 -1 -1 -1 -1 -1 12 14 16 18]


In [16]:
array = np.arange(0, 20, 2)
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
slice_array = array[0:5]    #Does not create a deep copy
slice_array[0] = 100
print(slice_array, array)

[100   2   4   6   8] [100   2   4   6   8  10  12  14  16  18]


In [18]:
array_copy = array.copy()
array_copy[:] = 6
print(array_copy, array)

[6 6 6 6 6 6 6 6 6 6] [100   2   4   6   8  10  12  14  16  18]


In [19]:
array_2d = np.linspace(start = 5, stop = 45, num = 9, dtype = int)
array_2d = array_2d.reshape(3, 3)


In [20]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
array_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

In [22]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
array[array % 2 == 0]

array([ 2,  4,  6,  8, 10])

# Numpy Operations

In [26]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [28]:
array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
array.sum()

45

In [32]:
array.mean()

4.5

In [36]:
array_2d = np.arange(0, 25).reshape(5, 5)
print(array_2d)
array_2d.sum()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


300

In [34]:
array_2d.sum(axis = 1)   # Row-wise sum (Across the columns)

array([ 10,  35,  60,  85, 110])

In [37]:
array_2d.sum(axis = 0)  # Column-wise sum (Across the rows)

array([50, 55, 60, 65, 70])